### ISSUE TITLE
Wordpress image: Request Entity Too Large

### ISSUE THREAD

**Issue by alexnetwork** [theraw/The-World-Is-Yours#6]
"Request Entity Too Large
The requested resource
/wp-admin/media-new.php
does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit."

How do I solve? I've also changed: client_max_body_size

**Comment by theraw** [comment]
try increase all memory limits into the `nginx.conf` also try increasing timeouts because if you take too much time to upload that will fail, 

also if your upload image or video or whatever is like 2M increase all things to like 10M don't add a very close number because that can fail based in other megas which site uses..

**Comment by alexnetwork** [comment]
Nope, not works :S
Request Entity Too Large
The requested resource
/wp-admin/media-new.php
does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit.

I used only reverse proxy..

**Comment by theraw** [comment]
Can you please let me know if you are using modsecurity or any other security check?

**Comment by alexnetwork** [comment]
I do not know.
On another server, that command works fine.
Only on that it does not work haha
Bho, however, thank you.

I do not use modsecurity.

**Comment by theraw** [comment]
can you provide the vhost config part which is used for reverse proxy?
